# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'inv_armas.ui'
#
# Created: Tue Jul  9 09:12:11 2013
#      by: PyQt5 UI code generator 5.0
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_win_armas(object):
    def setupUi(self, win_armas):
        win_armas.setObjectName("win_armas")
        win_armas.resize(724, 361)
        self.centralwidget = QtWidgets.QWidget(win_armas)
        self.centralwidget.setObjectName("centralwidget")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(30, 20, 120, 190))
        self.graphicsView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsView.setObjectName("graphicsView")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(200, 20, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.listView = QtWidgets.QListView(self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(540, 40, 171, 21))
        self.listView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.listView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listView.setObjectName("listView")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(200, 40, 46, 13))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(200, 60, 46, 13))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(200, 80, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(200, 100, 46, 13))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 220, 151, 131))
        self.groupBox.setObjectName("groupBox")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(10, 90, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(10, 60, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(10, 30, 46, 13))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.info_str = QtWidgets.QLabel(self.groupBox)
        self.info_str.setGeometry(QtCore.QRect(100, 30, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.info_str.setFont(font)
        self.info_str.setObjectName("info_str")
        self.info_dex = QtWidgets.QLabel(self.groupBox)
        self.info_dex.setGeometry(QtCore.QRect(100, 60, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.info_dex.setFont(font)
        self.info_dex.setObjectName("info_dex")
        self.info_int = QtWidgets.QLabel(self.groupBox)
        self.info_int.setGeometry(QtCore.QRect(100, 90, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.info_int.setFont(font)
        self.info_int.setObjectName("info_int")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(200, 130, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(200, 180, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.btn_salir = QtWidgets.QPushButton(self.centralwidget)
        self.btn_salir.setGeometry(QtCore.QRect(640, 330, 75, 23))
        self.btn_salir.setObjectName("btn_salir")
        self.info_modvalor = QtWidgets.QLabel(self.centralwidget)
        self.info_modvalor.setGeometry(QtCore.QRect(200, 210, 501, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.info_modvalor.setFont(font)
        self.info_modvalor.setObjectName("info_modvalor")
        self.info_mod = QtWidgets.QLabel(self.centralwidget)
        self.info_mod.setGeometry(QtCore.QRect(200, 150, 501, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.info_mod.setFont(font)
        self.info_mod.setObjectName("info_mod")
        self.info_dps = QtWidgets.QLabel(self.centralwidget)
        self.info_dps.setGeometry(QtCore.QRect(300, 100, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.info_dps.setFont(font)
        self.info_dps.setObjectName("info_dps")
        self.info_aps = QtWidgets.QLabel(self.centralwidget)
        self.info_aps.setGeometry(QtCore.QRect(300, 80, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.info_aps.setFont(font)
        self.info_aps.setObjectName("info_aps")
        self.info_dano = QtWidgets.QLabel(self.centralwidget)
        self.info_dano.setGeometry(QtCore.QRect(300, 60, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.info_dano.setFont(font)
        self.info_dano.setObjectName("info_dano")
        self.info_nivel = QtWidgets.QLabel(self.centralwidget)
        self.info_nivel.setGeometry(QtCore.QRect(300, 40, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.info_nivel.setFont(font)
        self.info_nivel.setObjectName("info_nivel")
        self.info_nombre = QtWidgets.QLabel(self.centralwidget)
        self.info_nombre.setGeometry(QtCore.QRect(300, 20, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.info_nombre.setFont(font)
        self.info_nombre.setObjectName("info_nombre")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(540, 20, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        win_armas.setCentralWidget(self.centralwidget)

        self.retranslateUi(win_armas)
        QtCore.QMetaObject.connectSlotsByName(win_armas)

    def retranslateUi(self, win_armas):
        _translate = QtCore.QCoreApplication.translate
        win_armas.setWindowTitle(_translate("win_armas", "Inventario Armas"))
        self.label.setText(_translate("win_armas", "Nombre"))
        self.label_2.setText(_translate("win_armas", "Nivel"))
        self.label_3.setText(_translate("win_armas", "Daño"))
        self.label_4.setText(_translate("win_armas", "Ataque (/sg)"))
        self.label_5.setText(_translate("win_armas", "DPS"))
        self.groupBox.setTitle(_translate("win_armas", "Requisitos"))
        self.label_8.setText(_translate("win_armas", "Inteligencia"))
        self.label_7.setText(_translate("win_armas", "Destreza"))
        self.label_6.setText(_translate("win_armas", "Fuerza"))
        self.info_str.setText(_translate("win_armas", "..."))
        self.info_dex.setText(_translate("win_armas", "..."))
        self.info_int.setText(_translate("win_armas", "..."))
        self.label_9.setText(_translate("win_armas", "Modificadores propios"))
        self.label_10.setText(_translate("win_armas", "Valor de los modificadores"))
        self.btn_salir.setText(_translate("win_armas", "Salir"))
        self.info_modvalor.setText(_translate("win_armas", "..."))
        self.info_mod.setText(_translate("win_armas", "..."))
        self.info_dps.setText(_translate("win_armas", "..."))
        self.info_aps.setText(_translate("win_armas", "..."))
        self.info_dano.setText(_translate("win_armas", "..."))
        self.info_nivel.setText(_translate("win_armas", "..."))
        self.info_nombre.setText(_translate("win_armas", "..."))
        self.label_11.setText(_translate("win_armas", "Listado"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    win_armas = QtWidgets.QMainWindow()
    ui = Ui_win_armas()
    ui.setupUi(win_armas)
    win_armas.show()
    sys.exit(app.exec_())

